### ISSUE TITLE
As an unauthenticated user, when I login at any point including the checkout, I should return back to the previous page that the I was on before the login.

### ISSUE THREAD

**Issue by Jwan622** [mikedao/the_pivot#165]
https://www.railstutorial.org/book/updating_and_deleting_users. look up redirect_to_back

**Comment by Jwan622** [comment]
https://www.railstutorial.org/book/updating_and_deleting_users

**Comment by mikedao** [comment]
You might also want to check our dinner dash, we had this implemented.

https://github.com/mikedao/dinner_dash
